//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group15_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string adminID { get; set; }
        public string adminName { get; set; }
        public string adminEmail { get; set; }
        public Nullable<System.DateTime> dateHired { get; set; }
    }
}
