//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group15_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public string customerID { get; set; }
        public string customerName { get; set; }
        public string customerShippingAddress { get; set; }
        public string customerBillingAddress { get; set; }
        public Nullable<System.DateTime> customerDOB { get; set; }
        public string customerGender { get; set; }
    }
}
