//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group15_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public string statusID { get; set; }
        public string orderStatus1 { get; set; }
        public Nullable<System.DateTime> statusDate { get; set; }
        public string adminUpdated { get; set; }
        public string customerID { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual CustomerInfo CustomerInfo { get; set; }
    }
}
